/**
 * \file    spinretcodes.h
 * \brief   Spin Digital return codes header file
 * \author  Chi Ching Chi <chi@spin-digital.com>
 *
 * Copyright/Rights of Use (Nutzungsrechte):
 * 2015-2020, Spin Digital Video Technologies GmbH
 * Berlin, Germany
 */

#pragma once
/** \addtogroup common SpinCommon
 *  @{
 */

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Spin Digital library return codes.
 */
enum SE_ReturnCodes {
  SD_OK = 0,
  SD_FAIL = -1,

  SD_E_GENERIC  = -101,
  SD_E_NOT_SUPPORTED   = -102,
  SD_E_OUT_OF_MEMORY   = -103,
  SD_E_ILLEGALPARAMS = -104,
  SD_E_BADALIGN = -105,
  SD_E_INVALIDPICTURE = -106,
  SD_E_INVALID_PICTURE = -106,
  SD_E_TIMEOUT = -107,
  SD_E_MISSING_INPUT_PICTURE = -108,
  SD_E_MISSING_OUTPUT_PICTURE = -109,
  SD_E_NOT_IMPLEMENTED = -110,
  SD_E_INPUT_OUTPUT_MISMATCH = -111,
  SD_E_FEATURE_NOT_SUPPORTED = -112,
  SD_E_PIXFMT_NOT_SUPPORTED = -113,
  SD_E_SAMFMT_NOT_SUPPORTED = -114,
  SD_E_DEVICE_NOT_FOUND = -115,
  SD_E_DEVICE_INIT_FAILED = -116,
  SD_E_INVALID_SOURCE = -117,
  SD_E_INVALID_FORMAT = -118,
  SD_E_BUFFER_NOT_FOUND = -119,
  SD_E_BUFFER_NOT_MAPPED = -120,
  SD_E_DEVICE_PORT_NOT_FOUND = -121,
  SD_E_DEVICE_PORT_NOT_ACTIVE = -122,
  SD_E_NOT_INITIALIZED = -123,
  SD_E_DEVICE_TYPE_MISMATCH = -124,
  SD_E_RATE_NOT_SUPPORTED = -125,
  SD_E_FILE_NOT_FOUND = -126,

  // SpinDec errors
  SD_E_CORRUPT_PARAMETERSET = -201,
  SD_E_CORRUPT_SLICEHEADER = -202,
  SD_E_CORRUPT_SEI = -203,
  SD_E_MISSING_PARAMETERSET = -204,
  SD_E_MISSING_PARENTSLICE = -205,
  SD_E_CANNOT_DECODE_LAYER = -206,
  SD_E_MISSING_REFPICS = -207,
  SD_E_CORRUPT_NALUNIT = -208,
  SD_E_MULTIPLE_AU_FOUND = -209,

  // SpinDec errors when decoding byte stream payload
  SD_E_RBSP_GENERIC = -300,
  SD_E_RBSP_MISSING_SLICES = -301,
  SD_E_RBSP_INVALID_SYNTAX = -302,
  SD_E_RBSP_BUFFER_OVERREAD = -303,

  // SpinFilter errors
  SD_E_INVALID_FILTER_CHAIN  = -402,
  SD_E_FILTER_CHAIN_NOT_INITIALIZED = -403,

  // SpinRender errors
  SD_E_INVALID_OVERLAY = -601,
  SD_E_EXCEED_MAXOVERLAYS = -602,
  SD_E_MIXED_DEVICE_TYPE = -604,
  SD_E_DEVICE_BUFFER_NOT_FOUND = -605,
  SD_E_INVALID_WINDOW_HANDLE = -606,
  SD_E_DEVICEMODE_NOT_SUPPORTED = -607,
  SD_E_CTRLOPNA = -608,

  // SpinAudRen errors
  SD_E_INVALID_OUTPUT = -701,
  SD_E_INVALID_OUTPUT_CHANNELS = -702,

  // SpinStream errors
  SD_E_DISCONTINUITY = -801,
  SD_E_INVALID_SID = -802,
  SD_E_INVALID_SRCADDR = -803,
  SD_E_INVALID_DESTADDR = -804,
  SD_E_PROT_NOT_SUPPORTED = -804,
  SD_E_WSASTARTUP = -805,
  SD_E_RTPSESSION_CREATE = - 806,

  // License errors
  SD_E_LICENSE_ERROR_BEGIN = -2001,
  SD_E_LICENSECONTAINER_NOT_FOUND  = -2001,
  SD_E_LICENSE_NOT_FOUND  = -2002,
  SD_E_FEATURE_NOT_AVAILABLE  = -2003,
  SD_E_LICENSE_NOT_VALID = -2004,
  SD_E_LICENSE_NOT_INITIALIZED = -2011,
  SD_E_LICENSE_ALREADY_INITIALIZED = -2012,
  SD_E_LICENSE_STILL_IN_USE = -2013,
  SD_E_LICENSESERVER_NOT_AVAILABLE = -2020,
  SD_E_LICENSESERVER_TIME_MISMATCH = -2021,
  SD_E_LICENSE_SYNTAX_UNEXPECTED = -2022,
  SD_E_LICENSE_ERROR_END = -2022,
} ;

#ifdef __cplusplus
}
#endif

/**@}*/
